//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARACARIZA
    {
        public int ID { get; set; }
        public string PLAKA { get; set; }
        public Nullable<System.DateTime> GIRISTARIHI { get; set; }
        public Nullable<System.DateTime> CIKISTARIHI { get; set; }
        public Nullable<decimal> ONFIYAT { get; set; }
        public Nullable<decimal> NETFIYAT { get; set; }
        public string ARIZADETAY { get; set; }
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
        public string PERSONELAD { get; set; }
        public string PERSONELSOYAD { get; set; }
    }
}
